
export const ActionTypes = {
    VOTE_POINT_CHANGE: 'VOTE_POINT_CHANGE',
    CHANGE_SORT_FILTER: 'CHANGE_SORT_FILTER',
    CHANGE_PAGE_SIZE_FILTER: 'CHANGE_PAGE_SIZE_FILTER',
    CHANGE_PAGE_INDEX_FILTER: 'CHANGE_PAGE_INDEX_FILTER',
    GET_PRODUCT_LIST: "GET_PRODUCT_LIST",
    CREATE_PRODUCT: "CREATE_PRODUCT",
}